### ISSUE TITLE
Use env from server middleware

### ISSUE THREAD

**Issue by alex88** [samtgarson/nuxt-env#19]
Thank you for this great library! I was wondering, is it possible to use this from a custom server middleware as defined in https://nuxtjs.org/api/configuration-servermiddleware ?

I've seen you inject `req.env` if on the server side however I don't see it in the server middleware request

I know I could use the env variables directly but it would be nice to have them available with the defaults as well and defined only in one place.

**Comment by blowsie** [comment]
Hi @alex88, I'm not a contributor to the plugin, but one way you could do this is simply extract the variables to a standalone .js file and import them in both your `serverMiddleware` and your `nuxt.config`

**Comment by alex88** [comment]
@blowsie yeah I think that's the way to go, seems the server middleware is completely separate from the nuxt.js app itself

**Comment by samtgarson** [comment]
For server side you should use environment variables that are accessible in your middleware and also in your nuxt env. 

This issue is due to the server middleware that nuxt env adds being run after your middleware so the env isn't loaded in yet... I don't think there's a way for us to choose where the mideware gets added. 

If you're not in a position to use environment variables it sounds like @blowsie's answer seems sensible.
